version: '3'
services:
  restapi-app:
    container_name: restapi-app
    image: symfony-pgsql-php:8.2
    expose:
      - 9000
    restart: unless-stopped
    volumes:
      - ./app/:/var/www/app:rw
      - ./cfg/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    working_dir: /var/www/app
    networks:
      - itacwit

  restapi-nginx:
    container_name: restapi-nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./cfg/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/:/var/www/app:rw
    networks:
      - itacwit

  restapi-postgres:
    image: postgres:latest
    container_name: restapi-postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'restapi'
    volumes:
      - restapi-postgres-data:/var/lib/pgsql/data:rw
    ports:
      - 5432:5432
    networks:
      - itacwit

volumes:
  restapi-postgres-data: { }

networks:
  itacwit:
    driver: bridge
